# Generated by Django 4.1.1 on 2022-10-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Comapany", "verbose_name_plural": "Companies"},
        ),
    ]
