# Generated by Django 4.1.1 on 2022-10-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        ("rooms", "0003_room_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={},
        ),
        migrations.RemoveField(
            model_name="room",
            name="topic",
        ),
        migrations.AddField(
            model_name="room",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jobs.company",
            ),
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
