# Generated by Django 4.1.1 on 2022-10-03 19:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("roll_number", models.CharField(max_length=10, unique=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("COMPUTER SCIENCE", "Cse"),
                            ("INFORMATION TECHNOLOGY", "It"),
                            ("ELECTRIC ENGINEERING", "Ee"),
                            ("CIVIL ENGINEERING", "Ce"),
                            ("TEXTILE ENGINEERING", "Te"),
                            ("MECHANICAL ENGINEERING", "Me"),
                            ("OTHER", "Ot"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(auto_now_add=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_superadmin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
