# Generated by Django 4.1.1 on 2022-10-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="roll_number",
            field=models.PositiveIntegerField(max_length=10, null=True, unique=True),
        ),
    ]
