# Generated by Django 4.1.1 on 2022-10-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_roll_number"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[],
        ),
        migrations.AddField(
            model_name="account",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to="photos/profiles"),
        ),
        migrations.AlterField(
            model_name="account",
            name="department",
            field=models.CharField(
                choices=[
                    ("CSE", "COMPUTER SCIENCE"),
                    ("IT", "INFORMATION TECHNOLOGY"),
                    ("EE", "ELECTRIC ENGINEERING"),
                    ("CE", "CIVIL ENGINEERING"),
                    ("TE", "TEXTILE ENGINEERING"),
                    ("ME", "MECHANICAL ENGINEERING"),
                    ("OT", "OTHER"),
                ],
                default="OT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="roll_number",
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
