# Generated by Django 4.1.1 on 2022-10-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_managers_account_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="roll_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
