# Generated by Django 4.1.1 on 2022-10-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_account_roll_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CSE", "COMPUTER SCIENCE"),
                    ("IT", "INFORMATION TECHNOLOGY"),
                    ("EE", "ELECTRIC ENGINEERING"),
                    ("CE", "CIVIL ENGINEERING"),
                    ("TE", "TEXTILE ENGINEERING"),
                    ("ME", "MECHANICAL ENGINEERING"),
                    ("OT", "OTHER"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
