# Generated by Django 4.1.1 on 2022-10-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_account_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                max_length=100, unique=True, verbose_name="email_address"
            ),
        ),
    ]
